# Project ------------------------------
project:
  type: website
  preview:
    port: 3210

# Website ------------------------------
website:
  title: "Resources Kit"
  repo-url: https://github.com/qtalr/resources
  repo-actions: [edit, issue]
  repo-link-target: "_blank"
  navbar:
    background: secondary
    foreground: light
    search: true
    left:
      - file: index.qmd
      - file: recipes/index.qmd
      - file: guides/index.qmd
    right:
      - file: instructors.qmd
      - icon: github
        href: https://github.com/qtalr/resources

  page-footer:
    left: "Developed by Jerid Francom"

# Formats ------------------------------
format:
  html:
    theme: flatly
    code-overflow: wrap
    css:
      - assets/styles.css
      - include/webex.css
    toc: true
    include-after-body: include/webex.js
    comments:
      hypothesis: true

# Reference and numbering ---------------

crossref:
  lst-title: "Snippet"
  lst-prefix: "Snippet"
  appendix-title: "App"
  appendix-delim: ":"

bibliography: [bibliography.bib, packages.bib]
biblio-style: apalike
link-citations: true

code-annotations: select
code-line-numbers: true

number-depth: 2

# Pandoc ------------------------------
execute:
  freeze: auto
  warning: false
  message: false

# Engine ------------------------------
knitr:
  opts_chunk:
    comment: ">"
    out.width: NULL
