# Project ------------------------------
project:
  type: website
  preview:
    port: 3210

# Website ------------------------------
website:
  title: "Quantitative Text Analysis: Resources"
  repo-url: https://github.com/qtalr/resources
  repo-actions: [edit, issue]
  repo-link-target: "_blank"
  navbar:
    background: secondary
    foreground: light
    search: true
    left:
      - file: index.qmd
      - file: recipes/index.qmd
      - file: guides/index.qmd
    right:
      - file: instructors.qmd
      - icon: github
        href: https://github.com/qtalr/resources

  page-footer:
    left: "Developed by Jerid Francom"

# Formats ------------------------------
format:
  html:
    theme: flatly
    css:
      - assets/styles.css
      - include/webex.css
    toc: true
    include-after-body: include/webex.js

bibliography: bibliography.bib
biblio-style: apalike
link-citations: true

# Pandoc ------------------------------
execute:
  freeze: auto
  warning: false
  message: false

# Engine ------------------------------
knitr:
  opts_chunk:
    comment: ">"
    out.width: NULL
